openapi: 3.0.0
info:
  title: blog
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-users
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      type: http
      scheme: basic
